---
title: "R Notebook"
output: html_notebook
---

Introducción to the Tidyverse

```{r}
library(gapminder)
library(dplyr)

```

Filtering

```{r}
gapminder %>% #pipe
  filter(year==1957)

```

Arrange

```{r}

gapminder %>% #pipe
  arrange(lifeExp) #LO ordena en orden ascendente por defecto

gapminder %>% #pipe
  arrange(desc(lifeExp))

```
filtering and arranging

```{r}
gapminder %>% #pipe %>%
  filter(year==1957) %>%
  arrange(desc(pop))

```
The verb mutate

```{r}

gapminder %>%
  mutate(lifeExpMonths = 12*lifeExp) #Cambia el valor original de lifeExp, lo multiplica por 12, unicamente afecta los resultados mostrados, el data set original se mantiene sin cambios.
#se utiliza para moficar una variable, o crear una nueva a partir de una existente.

```

Combining filter, mutate and arrange

```{r}

gapminder %>% 
  filter(year==2007) %>%
  mutate(lifeExpMonths = 12*lifeExp) %>%
  arrange(desc(lifeExpMonths))

```
```{r}

library(ggplot2)

gapminder_1952 <- gapminder %>%
  filter(year==1952) #para agregar mas filtro unicamente se van agregando separados por coma filter(year==1952, continent=="Asia")

gapminder_1952

ggplot(gapminder_1952, aes(x=pop, y=gdpPercap)) + 
  geom_point()

```

log Scaling

```{r}
ggplot(gapminder_1952, aes(x=pop, y=gdpPercap)) + 
  geom_point() +
  scale_x_log10() +
  scale_y_log10()

```

```{r}
ggplot(gapminder_1952, aes(x=pop, y=lifeExp, color=continent)) + 
  geom_point() +
  scale_x_log10() +
  scale_y_log10()
```

```{r}

ggplot(gapminder_1952, aes(x=pop, y=lifeExp, color=continent, size=gdpPercap)) + 
  geom_point() +
  scale_x_log10() 
 # scale_y_log10()
```

```{r}

ggplot(gapminder, aes(x=gdpPercap, y=lifeExp))+
  geom_point() +
  scale_x_log10()+
  facet_wrap(~ year)



```

