---
title: "R Notebook"
output: html_notebook
---
Operaciones Aritmeticas
```{r}
3 + 5

8-2
28 %% 6
```

Asignación de Variables. 
```{r}
x <- 20
y <- 3
total = x + y
total
```

```{r}  
my_character <- "universe"
my_character
```

```{r}
class(my_character)
```

Vectores
```{r}
numeric_vector <- c(1,10,49)
numeric_vector

character_vector <- c("a", "b", "c")
boolean_vector <- c(TRUE,FALSE,TRUE)

character_vector
boolean_vector

```
Nombrando un Vector
```{r}
poker_vector <- c(140, -50, 20, -120, 240)
roulette_vector <- c(-24, -50, 100, -350, 10)

names (poker_vector) <- c ("Monday", "Tuesday","wednesday","Thursday","Friday")
poker_vector

names (roulette_vector) <- c ("Monday", "Tuesday","wednesday","Thursday","Friday")
roulette_vector
```
Comparando y Seleccionando

```{r}
age <-17
result <- age >= 18
result

A_vector <- c(1,2,3)
b_vector <- c(4,5,6)
total_vector <- A_vector + b_vector
total_vector

total_daily <- poker_vector + roulette_vector
total_daily

total_poker <- sum(poker_vector)
total_poker

total_roulette <- sum (roulette_vector)
total_roulette

sum_total <- total_poker + total_roulette
sum_total

poker_vector
poker_vector[4]
poker_vector[c(1,3,4)]

roulette_vector [2:5]

poker_vector [c("Monday","Tuesday")]

poker_start <- poker_vector[c("Monday","Tuesday")]
mean (poker_start)

Selection_vector <- poker_vector > 0
Selection_vector

poker_winning_days <- poker_vector [Selection_vector]
poker_winning_days
```
Matrices

```{r}

matrix (1:9, byrow=TRUE,nrow=3)

```

```{r}

new_hope <- c(460.998, 314.4)
empire_strike <- c(2980.475,247.900)
return_jedi <- c(309.306, 165.8)

box_office <- c(new_hope, empire_strike, return_jedi )
box_office

star_wars_matrix <- matrix(box_office, byrow=TRUE, nrow=3)
star_wars_matrix


region <- c("US", "non-US")
titles <- c("A new Hope", "The Empire Strikes Back", "Retur of the Jedi ")

colnames (star_wars_matrix) <- region 
rownames (star_wars_matrix) <-titles

star_wars_matrix
```
rowSums()

```{r}
worldwide_vector <- rowSums(star_wars_matrix)
worldwide_vector

all_wars_varialbe <- cbind(star_wars_matrix, worldwide_vector )
all_wars_varialbe

worldwide_cols <- colSums(all_wars_varialbe)
worldwide_cols

all_wars_varialbe <- rbind(all_wars_varialbe, worldwide_cols)
all_wars_varialbe

```
Selection of matrix elements

```{r}

non_us_all <- all_wars_varialbe[1:3,2]
non_us_all

mean (non_us_all)
```
Arithmetic with matrices
```{r}
us_all <- all_wars_varialbe [1:3,1]
us_all <- us_all * 0.12
us_all
```



Factores
```{r}
sex_vector <- c("Male", "Female",  "Female", "Male", "Male" )
factor_sex_vector <- factor(sex_vector)
factor_sex_vector

temperature_vector <- c("High", "Low", "High", "Low", "Medium")
factor_temperatur_vector <- factor (temperature_vector, order=TRUE, levels=c("Low", "Medium", "High"))
factor_temperatur_vector

```

Factor Levels

```{r}
survey_vector <- c ("M", "F","F", "M", "M")
factor_survey_vector <- factor(survey_vector)

factor_survey_vector

levels(factor_survey_vector)  <- c ("Female", "Male")
factor_survey_vector
```
Summarizing a Factor

```{r}
summary(survey_vector)
summary (factor_survey_vector)

male <- factor_survey_vector[1]
male

female <- factor_survey_vector[2]
female


speed_vector <- c("medium", "slow", "slow", "medium", "fast")
factor_speed_vector <- factor (speed_vector, ordered =TRUE, levels = c("slow", "medium", "fast"))
factor_speed_vector


da2 <-factor_speed_vector [2]
da3 <-factor_speed_vector [5]

da2
da3

da2 < da3


```


```

