---
title: "R Notebook"
output: html_notebook
---

```{r}
library (tidyverse)
library(gapminder)
library(dplyr)

sets <- read_csv('sets.csv')
themes <- read_csv('themes.csv')
parts <- read_csv('parts.csv')
part_categories <- read_csv('part_categories.csv')


```
```{r}
counties <- read_csv("counties.csv")
counties

counties %>%
  select(state, county, population, professional:production)

counties %>%
  select(state, county, population, ends_with("work"), starts_with("income"))
#head(counties)
```
The rename verb

```{r}
counties %>%
  count(state) %>%
  rename(num_counties = n)

counties %>%
  select(state, county, poverty_rate = poverty)

```

Using transmute

```{r}

counties %>%
  transmute(state, county, population, density=population/land_area) %>%  #a diferencia de mutate, transmute solo mantiene las columanas indicadas o seleccionadas.
  filter(population > 1000000) %>%
  arrange(density)
```
```{r}
counties %>%
  rename(unemployment_rate = unemployment)

counties %>%
  select(state, county, contains("poverty"))
```
```{r}
counties %>%
  mutate(fraction_women = women/population)

counties %>%
  transmute(state, county, employment_rate = employed/ population)
```
Joining Data with dplyr

```{r}
sets
themes
```

```{r}
sets %>%
  inner_join(themes, by=c("theme_id"="id")) #Se definen cuales son las variables que se van a vincular, preservando el del primer set.
```


